// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp_0DP4HCzyTfa38otbTtWUdt58rwJkdo',
    appId: '1:908072160379:web:d2f33ad5fa2bd22c1566de',
    messagingSenderId: '908072160379',
    projectId: 'lulli-fy',
    authDomain: 'lulli-fy.firebaseapp.com',
    storageBucket: 'lulli-fy.firebasestorage.app',
    measurementId: 'G-D5SZCMR0HZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhGHlxakwKw9x4xzgfmmzHYpEF37lTpbU',
    appId: '1:908072160379:android:d18fbac46d805d251566de',
    messagingSenderId: '908072160379',
    projectId: 'lulli-fy',
    storageBucket: 'lulli-fy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxxB0Qh7tMfksaLcrI7RW3KBZDEH7ruJQ',
    appId: '1:908072160379:ios:323fd9aca10b97aa1566de',
    messagingSenderId: '908072160379',
    projectId: 'lulli-fy',
    storageBucket: 'lulli-fy.firebasestorage.app',
    iosBundleId: 'com.example.sp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxxB0Qh7tMfksaLcrI7RW3KBZDEH7ruJQ',
    appId: '1:908072160379:ios:323fd9aca10b97aa1566de',
    messagingSenderId: '908072160379',
    projectId: 'lulli-fy',
    storageBucket: 'lulli-fy.firebasestorage.app',
    iosBundleId: 'com.example.sp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBp_0DP4HCzyTfa38otbTtWUdt58rwJkdo',
    appId: '1:908072160379:web:c9416c04e4b1004f1566de',
    messagingSenderId: '908072160379',
    projectId: 'lulli-fy',
    authDomain: 'lulli-fy.firebaseapp.com',
    storageBucket: 'lulli-fy.firebasestorage.app',
    measurementId: 'G-33W27J0RHR',
  );
}
